#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds001928-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds001928-mriqc/.reproman/jobs/local/20220304-051136-970e/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds001928-mriqc/.reproman/jobs/local/20220304-051136-970e/stderr

#SBATCH --nodes=8
#SBATCH --ntasks=40
#SBATCH --time=8:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds001928-mriqc/.reproman/jobs/local/20220304-051136-970e

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 39); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun